name: CI/CD Pipeline

env:
  MAIN_BRANCH: main
  STAGING_BRANCH: staging
  DEVELOP_BRANCH: develop

on:
  push:
    branches:
      - ${{ env.MAIN_BRANCH }}
      - ${{ env.STAGING_BRANCH }}
      - ${{ env.DEVELOP_BRANCH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        run: echo "Deploying to production..."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        run: echo "Deploying to staging..."

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        run: echo "Deploying to development..."
