name: CI/CD Pipeline

env:
  MAIN_BRANCH: main
  STAGING_BRANCH: staging
  DEVELOP_BRANCH: develop

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 and deploy
        # run: echo "Deploying to production..."
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Lấy khóa SSH từ secrets
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-44-205-253-61.compute-1.amazonaws.com "cd /var/www/laravel12-gh && sudo git pull origin main && sudo php artisan migrate --force && sudo php artisan cache:clear"

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 and deploy
        # run: echo "Deploying to staging..."
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Lấy khóa SSH từ secrets
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-44-205-253-61.compute-1.amazonaws.com "cd /var/www/laravel12-gh && sudo git pull origin staging && sudo php artisan migrate --force && sudo php artisan cache:clear"

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 and deploy
        # run: echo "Deploying to development..."
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Lấy khóa SSH từ secrets
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-44-205-253-61.compute-1.amazonaws.com "cd /var/www/laravel12-gh && sudo git pull origin develop && sudo php artisan migrate --force && sudo php artisan cache:clear"
